name: "PR Test Generator"
description: "Auto-generate and run end-to-end tests for Pull Requests using Claude API and Magnitude"
author: "Your Name"

branding:
  icon: "zap"
  color: "blue"

inputs:
  claude-api-key:
    description: "Claude API Key from Anthropic"
    required: true
  github-token:
    description: "GitHub Token for API access"
    required: true
    default: ${{ github.token }}
  test-examples:
    description: "Custom test examples to guide Claude (optional)"
    required: false
    default: |
      // Example Magnitude tests:
      const { startBrowserAgent } = require('magnitude-core');
      require('dotenv').config();

      async function runTests() {
        const agent = await startBrowserAgent({
          url: process.env.PREVIEW_URL || 'http://localhost:3000',
          narrate: true,
          browser: {
            launchOptions: { headless: true },
            contextOptions: { viewport: { width: 1280, height: 720 } 
          }
        });
        
        try {
          console.log('Test: Navigate to homepage');
          await agent.act('Navigate to the homepage');
          const title = await agent.extract('Get the main heading text');
          console.log('Page title:', title);
          
          console.log('All tests completed successfully');
        } finally {
          await agent.stop();
        }
      }

      runTests().catch(error => {
        console.error('Test suite failed:', error);
        process.exit(1);
      });
  output-dir:
    description: "Directory to save generated test files"
    required: false
    default: ".github/generated-tests"
  timeout:
    description: "Test execution timeout in seconds"
    required: false
    default: "120"
  comment-on-pr:
    description: "Whether to comment test results on the PR"
    required: false
    default: "true"
  wait-for-preview:
    description: "Wait for preview URLs to appear in PR comments (in seconds)"
    required: false
    default: "60"
  base-url:
    description: "Base URL to use for tests (overrides preview URL detection)"
    required: false
  test-user-email:
    description: "Email for test user authentication (if preview requires login)"
    required: false
  test-user-password:
    description: "Password for test user authentication (if preview requires login)"
    required: false

outputs:
  test-results:
    description: "JSON string containing test execution results"
  test-file-path:
    description: "Path to the generated test file"
  tests-passed:
    description: "Boolean indicating if all tests passed"

runs:
  using: "node20"
  main: "dist/index.js"
